export const footerStaticNavigation = [
  {
    name: 'Contact',
    url: 'contact',
  },
  {
    name: 'FAQs',
    url: 'faqs',
  },
  {
    name: 'Privacy Policy',
    url: 'privacy-policy',
  },
  {
    name: 'Terms & Conditions',
    url: 'terms-conditions',
  },
  {
    name: 'Blogs',
    url: 'blogs',
  },
];

export const productCategories = {
  Apparel: [
    'T-Shirts',
    'Aprons',
    'Polos',
    'Sweatshirts',
    'Jackets',
    'Accessories',
    'Teamwear',
    'Shirts',
    'Socks',
  ],
  Bags: [
    'Tote Bags',
    'Cooler Bags',
    'Satchel Bags',
    'Backpacks',
    'Duffle Bags',
    'Laptop Bags',
    'Wine Carriers',
    'Jute Bags',
    'Paper Bags',
    'Drawstring Bags',
    'Other Bags',
    'Other Bags',
    'Shopping Bags',
    'Lunch Bags',
    'Conference Bags',
    'Gift Bags',
    'Cotton Bags',
    'Toiletry Bags',
    'Sport Bags',
    'Dry Bags',
  ],
  Brands: [
    'XD Design',
    'Swiss Peak',
    'Pierre Cardin',
    'Lamy',
    'Moleskine',
    "SOL'S",
    'Titleist',
    'BLUNT',
    'CamelBak',
    'Peros',
    'Skullcandy',
    'Skullcandy',
    'Osprey',
    'Luigi Bormioli',
    'Keepsake',
    'Natura',
  ],
  Business: [
    'Stationery',
    'Portfolios',
    'Notebooks',
    'Lanyards',
    'Desk Items',
    'Highlighters',
    'ID Holders',
    'Rulers',
    'Pencil Cases',
    'Sticky Notes',
    'Note Pads',
    'Note Pads',
  ],
  Collections: [
    'Real Estate',
    'Health & Beauty',
    'Children',
    'Fundraising',
    'Trades',
    'Agriculture',
    'Sports & Fitness',
    'Tradeshows',
    'Conference',
    'Conference',
    'Automotive',
    'Natural',
    'Festivals & Events',
    'Summer',
    'Winter',
    'Travel',
    'Logistics',
    'Rest Homes',
    'Rest Homes',
    'Golf',
    'Price Buster',
    'Safety',
    'Mailable Items',
    'Hospitality',
  ],
  Drinkware: [
    'Travel Mugs',
    'Ceramic Mugs',
    'Glassware',
    'Cups & Tumblers',
    'Sports Shakers',
    'Coffee Cups',
    'Drinkware Presentation',
    'Drink Bottles - Plastic',
    'Drink Bottles - Metal',
    'Drink Bottles - Glass',
    'Drink Bottles',
    'Drink Bottles',
    'Flasks',
    'Outdoor Hospitality',
    'Teaware',
  ],
  Headwear: [
    'Caps',
    'Beanies',
    'Caps - Flat Peak',
    'Caps - Trucker',
    'Sports Headwear',
    'Bucket Hats',
    'Visors',
    'Wide Brims',
    'Accessories',
    'Caps - 5 Panel',
    'Caps - 6 Panel',
    'Caps - 6 Panel',
    'School Headwear',
    'Headwear Express',
    'Straw Hats',
    'Scarves',
  ],
  Leisure: [
    'Sport',
    'Sunglasses',
    'Golf',
    'Umbrellas',
    'Travel',
    'Home and Living',
    'Coasters',
    'Chairs',
    'Picnic & BBQ',
    'Towels',
    'Blankets',
    'Blankets',
    'Camping & Outdoors',
    'Cheese & Serving Boards',
    'Sports Balls',
    'Games & Puzzles',
    'Tools',
  ],
  Pens: [
    'Plastic',
    'Metal',
    'Mix and Match',
    'Novelty',
    'Presentation',
    'Refills',
    'Deluxe',
    'Stylus',
    'Highlighter',
    'Natural',
    'Blue Refill',
    'Blue Refill',
    'Black Refill',
  ],
  Personal: [
    'Lotions & Sunscreens',
    'Lip Balms',
    'Hand Sanitiser',
    'Personal Care',
    'First Aid',
    'Face Masks',
    'Candles & Diffusers',
  ],
  Print: [
    'Magnets',
    'Resin Labels',
    'Business Cards',
    'Ad Labels',
    'Pads & Planners',
    'Ribbons & Accessories',
  ],
  Promotion: [
    'Stubby & Can Holders',
    'Confectionery',
    'Stress Items',
    'Badges',
    'Bar Mats',
    'Promotion',
    'Beach Balls',
    'Bottle Openers',
    'Wristbands',
    'Fidget Items',
    'Temporary Tattoos',
    'Temporary Tattoos',
    'Plush Toys',
    'Key Rings',
  ],
  Technology: [
    'Flash Drives',
    'Speakers',
    'Tech Accessories',
    'Headphones',
    'Power Banks',
    'Tablet Cases',
    'Laptop Bags',
    'Phone Wallets',
    'Car USB Chargers',
    'Wireless Chargers',
    'Charging Cables',
    'Charging Cables',
    'Car Phone Holders',
    'Screen Cleaners',
    'USB Hubs',
    'Earbuds',
    'Mouse Mats',
  ],
  'World Source': [
    'Novelty Pens',
    'Stylus Pens',
    'Highlighter Pens',
    'Drinkware',
    'Selfie Sticks',
    'Phone & Tablet Cases',
    'Tech Accessories',
    'Travel',
    'USB Hubs',
    'Styluses',
    'Car Chargers',
    'Ear Buds',
    'Phone Stands',
    'Screen Cleaners',
    'Belt Bags',
    'Toiletry Bags',
    'Sunglasses',
    'Golf',
    'Towels',
    'Bottle Openers',
    'Torches & Lights',
    'Key Rings',
    'Tools',
    'Photo Frames',
    'Fans',
    'Kitchen',
    'Notes & Flags',
    'Stationery',
    'Highlighters',
    'Personal',
    'Card Holders',
    'Sewing Kits',
    'Promotional',
    'Drink Coolers',
    'Leisure',
    'Coin Pouches',
    'Fitness',
    'Novelty',
    'Tote Bags',
    'Pill Boxes',
    'Hot/Cold Packs',
    'Bags',
    'Backpacks',
    'Headwear',
    'Confectionery',
    'Wallets',
  ],
};

export const bannerNavbarItems = [
  {
    name: 'Collection',
    dropdown: true,
    dropdownValues: [
      'Winter',
      'Travel',
      'Tradeshows',
      'Trades',
      'Summer',
      'Sports & Fitness',
      'Safety',
      'Rest Homes',
      'Real Estate',
      'Price Buster',
      'Natural',
      'Mailable Items',
      'Logistics',
      'Hospitality',
      'Health & Beauty',
      'Golf',
      'Fundraising',
      'Festivals & Events',
      'Conference',
      'Children',
      'Automotive',
      'Agriculture',
    ],
  },
  {
    name: 'Brands',
    dropdown: true,
    dropdownValues: [
      'XD Design',
      'Titleist',
      'Swiss Peak',
      "SOL'S",
      'Skullcandy',
      'Pierre Cardin',
      'Peros',
      'Osprey',
      'Natura',
      'Moleskine',
      'Luigi Bormioli',
      'Lamy',
      'Keepsake',
      'CamelBak',
      'BLUNT',
    ],
  },
  {
    name: 'Branding Solutions',
    dropdown: true,
    dropdownValues: [
      'Colourflex Transfer',
      'Debossing',
      'Digital Labe',
      'Digital Print',
      'Direct Digital',
      'Embroidery',
      'Imitation Etch',
      'Laser Engraving',
      'Pad Print',
      'Resin Coated Finish',
      'Rotary Digital Print',
      'Rotary Screen Print',
      'Screen Print',
      'Silicone Digital Print',
      'Sublimation Print – Dye Sublimation',
    ],
  },
  { name: 'Our Story', dropdown: false },
  { name: 'Credit Application', dropdown: false },
  { name: 'Gift Card', dropdown: false },
];

export const bannerImages = [
  'https://welovebrandings.spreadagency.co.nz/public/assets/images/featuredbanner/1647852513thumb2.png',
  'https://welovebrandings.spreadagency.co.nz/public/assets/images/featuredbanner/1647852484thumb1.png',
  'https://welovebrandings.spreadagency.co.nz/public/assets/images/featuredbanner/1647852513thumb2.png',
  'https://welovebrandings.spreadagency.co.nz/public/assets/images/featuredbanner/1647852513thumb2.png',
  'https://welovebrandings.spreadagency.co.nz/public/assets/images/featuredbanner/1647852484thumb1.png',
  'https://welovebrandings.spreadagency.co.nz/public/assets/images/featuredbanner/1647852513thumb2.png',
  'https://welovebrandings.spreadagency.co.nz/public/assets/images/featuredbanner/1647852513thumb2.png',
];

export const brandImages = [
  'https://welovebrandings.spreadagency.co.nz/public/assets/images/shopbybrands/16480039992-brand-pku60dlptbqb6yewnfq8i2tyss5lb8ul4f5ivqywv4.png',
  'https://welovebrandings.spreadagency.co.nz/public/assets/images/shopbybrands/16480041155-brand-new-pku6le9sa8nqdfy2alkhf2m7eqvww38e6xz9m1nqn4.png',
  'https://welovebrandings.spreadagency.co.nz/public/assets/images/shopbybrands/16480041309-brand-pku6113osilakobkgcwgppvh6a16gldjdbw229r3j4.png',
  'https://welovebrandings.spreadagency.co.nz/public/assets/images/shopbybrands/164800414210-brand-pku6121izcmkwaa7avb3a7mxrnwjoah9pgjjjjppcw.png',
  'https://welovebrandings.spreadagency.co.nz/public/assets/images/shopbybrands/164800415711-brand-pku654ob7y6s7gjj880qxuflwfbevuco5j4zy67jog.png',
  'https://welovebrandings.spreadagency.co.nz/public/assets/images/shopbybrands/16479462483-brand-pku60iawztvk4h2vi4rxbum9aklu6nawmqucgqiyzk.png',
  'https://welovebrandings.spreadagency.co.nz/public/assets/images/shopbybrands/16479464754-brand-pku60ovsbo4kdqtbfpmbbayhg9peoj10zneqto97s0.png',
  'https://welovebrandings.spreadagency.co.nz/public/assets/images/shopbybrands/16479464986-brand-pku60tkz9uazzsmho9ng5rrsf728r0jooao68228ww.png',
  'https://welovebrandings.spreadagency.co.nz/public/assets/images/shopbybrands/16479465268-brand-pku60z80euipxgearc37kqcjziag1762p2l33ptvvk.png',
  'https://welovebrandings.spreadagency.co.nz/public/assets/images/shopbybrands/16479496387-brand-pku60vgnnidkn0jrdagparaplysz6er5cjz56lzgkg.png',
];

export const catalogueImages = [
  'https://welovebrandings.spreadagency.co.nz/public/assets/images/banners/1648005404img-03.png',
  'https://welovebrandings.spreadagency.co.nz/public/assets/images/banners/1648005421img-04.png',
  'https://welovebrandings.spreadagency.co.nz/public/assets/images/banners/1648005442img-06.png',
  'https://welovebrandings.spreadagency.co.nz/public/assets/images/banners/1648005459img-07.png',
  'https://welovebrandings.spreadagency.co.nz/public/assets/images/banners/1648005421img-04.png',
  'https://welovebrandings.spreadagency.co.nz/public/assets/images/banners/1648005404img-03.png',
  'https://welovebrandings.spreadagency.co.nz/public/assets/images/banners/1648005421img-04.png',
  'https://welovebrandings.spreadagency.co.nz/public/assets/images/banners/1648005442img-06.png',
  'https://welovebrandings.spreadagency.co.nz/public/assets/images/banners/1648005459img-07.png',
];

export const dummyProduct = {
  id: '4655b708-037f-4767-a2e9-d441af564829',
  is_active: 'True',
  name: 'Sonnet Cotton Tote Bag',
  slug: 'sonnet-cotton-tote-bag',
  sku: null,
  code: '100566',
  short_description: null,
  long_description:
    'Environmentally-conscious tote bag with longer handles so it can be carried on a shoulder. It is manufactured from 135gsm unbleached natural cotton.',
  features: null,
  status: 'NORMAL',
  minimum_order_quantity_number: 100,
  minimum_order_quantity_price: 1.4,
  additional_information: [
    {
      id: '0c869f08-4ffc-406d-b319-97b3a74ec760',
      is_active: 'True',
      specifications: [
        {
          specification: 'Capacity',
          description: '1L',
        },
      ],
      materials: [
        {
          component: 'Body',
          material: 'Cotton',
        },
      ],
      dimensions: [
        'H 410mm x W 380mm (excludes handles)',
        'Handle Length: 580mm',
      ],
      sizing: [],
      packaging: 'Loose Packed',
      carton: {
        length: 47,
        width: 42,
        height: 42,
        weight: '16.20',
        quantity: 250,
      },
      colours: {
        colours: 'Natural.',
        secondary_colour: '',
        colours_3: '',
        standard_colours: 'natural ',
      },
    },
  ],
  images: [
    {
      id: '2f92ed1d-cf86-4cf5-945c-0392c6c26a2d',
      is_active: 'True',
      name: '100566-0.jpg',
      type: 'IMAGE',
      url: 'https://assets.trends.nz/resizer/470/100566-0.jpg',
      caption: 'Main',
      is_thumbnail: false,
    },
  ],
  branding_information: [
    {
      id: '29e2dbd1-ac45-4867-8ffe-672907ab18a6',
      is_active: 'True',
      full_colour: true,
      mix_and_match: false,
      branding_area: '250mm x 200mm',
      description: 'Colourflex Transfer',
      branding_unit_price: 2.3,
      branding_set_up_price: 40,
      branding_solution: {
        title: 'Colourflex Transfer\n',
      },
    },
    {
      id: '02368795-2e93-4c78-8f9d-dce3239a1ba3',
      is_active: 'True',
      full_colour: true,
      mix_and_match: false,
      branding_area: '250mm x 250mm',
      description: 'Screen Print Per Colour/Position',
      branding_unit_price: 0.5,
      branding_set_up_price: 40,
      branding_solution: {
        title: 'Screen Print\n',
      },
    },
  ],
  pricing: null,
};
